import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@progress/kendo-theme-default/dist/all.css";
import './global.css'

const geistSans = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable}`}>
      <body
        className={`antialiased k-body`}
      >
        {children}
      </body>
    </html>
  );
}
